# GitHub Actions for GEOS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>
# Based on AZP configuration by Mateusz Loskot <mateusz at loskot dot net>

name: 'CI'

on:
  push:
    paths-ignore:
      - 'web/**'
  pull_request:
    paths-ignore:
      - '**/.md'

jobs:
  linux:
    name: 'Linux'
    strategy:
      matrix:
        ci:
        - cxx_compiler: g++
          c_compiler: gcc
          build_type: Coverage
          cxxstd: 11
          arch: 64
          packages: g++
          cmake: 3.15.*
          cmake_extra: '-DBUILD_BENCHMARKS=ON'
          os: ubuntu-18.04
          
        - cxx_compiler: g++-4.8
          c_compiler: gcc-4.8
          build_type: Release
          cxxstd: 11
          arch: 32
          packages: 'g++-4.8-multilib gcc-4.8-multilib g++-multilib gcc-multilib'
          cmake: 3.13.*
          os: ubuntu-18.04

        - cxx_compiler: g++-5
          c_compiler: gcc-5
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'g++-5-multilib gcc-5-multilib'
          cmake: 3.13.*
          os: ubuntu-18.04

        - cxx_compiler: g++-6
          c_compiler: gcc-6
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'g++-6-multilib gcc-6-multilib'
          cmake: 3.13.*
          os: ubuntu-18.04

        - cxx_compiler: g++-7
          c_compiler: gcc-7
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'g++-7-multilib gcc-7-multilib'
          cmake: 3.13.*
          os: ubuntu-18.04

        - cxx_compiler: g++-8
          c_compiler: gcc-8
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'g++-8-multilib gcc-8-multilib'
          cmake: 3.13.*
          os: ubuntu-18.04

        - cxx_compiler: g++-9
          c_compiler: gcc-9
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'g++-9-multilib gcc-9-multilib'
          cmake: 3.13.*
          os: ubuntu-18.04
        
        - cxx_compiler: g++-10
          c_compiler: gcc-10
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'g++-10-multilib gcc-10-multilib'
          cmake: 3.13.*
          os: ubuntu-18.04
        
        - cxx_compiler: g++-11
          c_compiler: gcc-11
          build_type: Release
          cxxstd: 17
          arch: 64
          packages: 'g++'
          cmake: 3.22.*
          os: ubuntu-22.04
        
        - cxx_compiler: g++-11
          c_compiler: gcc-11
          build_type: Release
          cxxstd: 20
          arch: 64
          packages: 'g++'
          cmake: 3.22.*
          os: ubuntu-22.04

        - cxx_compiler: clang++-7
          c_compiler: clang-7
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'clang-7'
          cmake: 3.13.*
          os: ubuntu-18.04

        - cxx_compiler: clang++-8
          c_compiler: clang-8
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'clang-8'
          cmake: 3.13.*
          os: ubuntu-18.04

        - cxx_compiler: clang++-9
          c_compiler: clang-9
          build_type: Release
          cxxstd: 11
          arch: 64
          packages: 'clang-9'
          cmake: 3.13.*
          os: ubuntu-18.04
        
        - cxx_compiler: clang++-10
          c_compiler: clang
          build_type: Debug
          cxxstd: 11
          arch: 64
          packages: 'clang'
          cmake: 3.17.*
          os: ubuntu-20.04
        
        - cxx_compiler: clang++-10
          c_compiler: clang
          build_type: Release
          cxxstd: 14
          arch: 64
          packages: 'clang'
          cmake: 3.17.*
          os: ubuntu-20.04


    runs-on: ${{ matrix.ci.os }}
    steps:

    - name: 'Install'
      run: |
        set -e
        uname -a
        sudo -E apt-get update
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install make doxygen python3-pip valgrind ${{ matrix.ci.packages }}
        python3 -m pip install --disable-pip-version-check --user cmake==${{ matrix.ci.cmake }}
        echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Build'
      env:
        CFLAGS: "-m${{ matrix.ci.arch }}"
        CXXFLAGS: "-m${{ matrix.ci.arch }}"
      run: |
        set -e
        mkdir build.cmake
        cd build.cmake
        cmake --version
        cmake ${{ matrix.ci.cmake_extra }} -DCMAKE_C_COMPILER=${{ matrix.ci.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.ci.cxx_compiler }} -DCMAKE_CXX_STANDARD=${{ matrix.ci.cxxstd }} -DBUILD_DOCUMENTATION=YES -DCMAKE_BUILD_TYPE=${{ matrix.ci.build_type }} ..
        make -j 2
        cmake --build . --target docs

    - name: Test
      run: |
        set -e
        cd build.cmake
        ctest --output-on-failure .

    # Run the all-unit-tests under
    # the memory checker when we have Debug symbols
    # available. Change to ^all to also check all-xml-tests
    - name: Valgrind
      if: matrix.ci.build_type == 'Debug'
      run: |
        set -e
        cd build.cmake
        ctest --output-on-failure \
          --overwrite MemoryCheckCommandOptions="--leak-check=full --error-exitcode=100" \
          -R ^all-unit -C Valgrind -T memcheck

    - name: 'Upload Valgrind Log'
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: valgrind-log
        path: build.cmake/Testing/Temporary/MemoryChecker.**.log
        retention-days: 1

    - name: Upload Coverage to Codecov
      if: matrix.ci.build_type == 'Coverage'
      run: |
        curl -o codecov.sh https://codecov.io/bash
        bash codecov.sh
      shell: bash

  windows-mingw:
    name: 'Windows (mingw-w64, Debug, 11, x86_64, windows-2019)'
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Setup'
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make
        update: true

    - name: 'Build'
      run: |
       mkdir build
       cd build
       cmake --version
       cmake -DCMAKE_BUILD_TYPE=Debug -G"MSYS Makefiles" ..
       cmake --build . -j 2

    - name: 'Test'
      run: |
       cd build
       ctest --output-on-failure .

  windows-mingw-release:
    name: 'Windows (mingw-w64, Release, 11, x86_64, windows-2019)'
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Setup'
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make
        update: true

    - name: 'Build'
      run: |
       mkdir build
       cd build
       cmake --version
       cmake -DCMAKE_BUILD_TYPE=Release -G"MSYS Makefiles" ..
       cmake --build . -j 2

    - name: 'Test'
      run: |
       cd build
       ctest --output-on-failure .

  windows-msvc-22:
    name: 'Windows (Visual Studio 2022, Debug, windows-2022)'
    runs-on: windows-2022
    steps:
    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Build'
      run: |
       mkdir build
       cd build
       cmake --version
       cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=14 -DBUILD_SHARED_LIBS=ON ..
       cmake --build . --config Debug -j 2

    - name: 'Test'
      run: |
       cd build
       ctest --output-on-failure -C Debug

  windows-msvc-19:
    name: 'Windows (Visual Studio 2019, Release, windows-2019)'
    runs-on: windows-2019
    steps:
    - name: 'Check Out'
      uses: actions/checkout@v3

    - name: 'Build'
      run: |
       mkdir build
       cd build
       cmake --version
       cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 -DBUILD_SHARED_LIBS=ON ..
       cmake --build . --config Release -j 2

    - name: 'Test'
      run: |
       cd build
       ctest --output-on-failure -C Release

  macos:
    name: 'macOS clang'
    strategy:
      matrix:
        xcode: [11.7, 12.4, 13.2.1]
        cxxstd: [11]
        build_type: ['Debug']
        include:
          - xcode: 13.2.1
            cxxstd: 14
            build_type: Debug
          - xcode: 13.2.1
            cxxstd: 17
            build_type: Debug
          - xcode: 13.2.1
            cxxstd: 20
            build_type: Debug
          
    runs-on: macos-11
    steps:

    - name: 'Install'
      env:
        XCODE_APP: /Applications/XCode_${{ matrix.xcode }}.app
      run: |
        set -e
        uname -a
        sudo xcode-select -switch ${XCODE_APP}
        which clang++
        clang++ --version

    - name: 'Check Out'
      uses: actions/checkout@v2

    - name: 'Build'
      env:
        BUILD_TYPE: ${{ matrix.build_type }}
        CXX_STANDARD: ${{ matrix.cxxstd }}
      run: |
        set -e
        mkdir build
        cd build
        cmake --version
        cmake -DCMAKE_CXX_STANDARD=${CXX_STANDARD} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
        cmake --build . --config ${BUILD_TYPE} -j 3

    - name: 'Test'
      run: |
        cd build
        ctest -V --output-on-failure -C ${BUILD_TYPE}


  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: |
        set -e
        sudo -E apt-get update
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install cppcheck
        
    - name: 'Check Out'
      uses: actions/checkout@v2

    - name: 'cppcheck'
      run: |
        ./tools/cppcheck.sh


  cmake-subproject:
    name: 'CMake Subproject'
    runs-on: ubuntu-18.04
    steps:
    - name: 'Install'
      run: |
        set -e
        uname -a
        sudo -E apt-get update
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install make python3-pip g++
        python3 -m pip install --disable-pip-version-check --user cmake==3.13.*
        echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

    - name: 'Check Out'
      uses: actions/checkout@v3
      with:
        path: geos

    - name: 'CMake Superbuild'
      run: |
        set -e
        cp geos/tests/superbuild.CMakeLists.txt ./CMakeLists.txt
        cp geos/examples/capi_read.c .
        cmake --version
        cmake -S . -B build
        cmake --build build -j 2
        build/capi_read
        test ! -f build/geos/bin/test_geos_unit || { echo "Error: GEOS tests were built" 1>&2 ; exit 1; }
