name: windows_gcc
jobs:
  windows_gcc:
    runs-on-: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-mys2@v2
      with:
        install: gcc cmake make
      run: mkdir build
      run: cd build && cmake .. && cmake --build . && ctest




