name: Windows CI
on: [push, pull_request]

jobs:
  windows_gcc:
    name: 'Windows msys2'
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make
    - run: |
       mkdir build
       cd build
       cmake -G"MSYS Makefiles" ..
       cmake --build . -j 2
       ctest




