name: Windows CI
on: [push, pull_request]

jobs:
  windows_gcc:
    name: 'Windows msys2'
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-mys2@v2
      with:
        install: gcc cmake make
    - run: mkdir build
    - run: cd build && cmake .. && cmake --build . && ctest




